<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="LAPTOP-N04AR20A" name="TestNGDemo.TestNGListenerDemo2" tests="7" failures="1" timestamp="03 Aug 2019 15:47:27 GMT" time="0.024" errors="0">
  <testcase name="test6" time="0.016" classname="TestNGDemo.TestNGListenerDemo2">
    <skipped/>
  </testcase> <!-- test6 -->
  <testcase name="test6" time="0.002" classname="TestNGDemo.TestNGListenerDemo2">
    <skipped/>
  </testcase> <!-- test6 -->
  <testcase name="test7" time="0.002" classname="TestNGDemo.TestNGListenerDemo2"/>
  <testcase name="test6" time="0.002" classname="TestNGDemo.TestNGListenerDemo2">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at TestNGDemo.TestNGListenerDemo2.test6(TestNGListenerDemo2.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test6 -->
  <testcase name="test6" time="0.001" classname="TestNGDemo.TestNGListenerDemo2">
    <skipped/>
  </testcase> <!-- test6 -->
  <testcase name="test8" time="0.001" classname="TestNGDemo.TestNGListenerDemo2"/>
  <testcase name="test5" classname="TestNGDemo.TestNGListenerDemo2">
    <skipped/>
  </testcase> <!-- test5 -->
</testsuite> <!-- TestNGDemo.TestNGListenerDemo2 -->
